"""add_created_at_to_shares

Revision ID: 37d3ad3e8f10
Revises: 7daa63a3f881
Create Date: 2026-04-16 14:38:48.574923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37d3ad3e8f10'
down_revision: Union[str, None] = '7daa63a3f881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shares', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shares', 'created_at')
    # ### end Alembic commands ###
