"""init all tables

Revision ID: 7daa63a3f881
Revises: 
Create Date: 2026-04-14 16:34:48.886078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7daa63a3f881'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='分类名称'),
    sa.Column('slug', sa.String(length=100), nullable=False, comment='URL标识，唯一'),
    sa.Column('description', sa.Text(), nullable=True, comment='分类描述'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父分类ID，为空则是顶级分类'),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='标签名称，唯一'),
    sa.Column('slug', sa.String(length=50), nullable=False, comment='URL标识，唯一'),
    sa.Column('color', sa.String(length=20), nullable=True, comment='标签颜色，如 #FF5733'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名，唯一'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='邮箱，唯一'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='bcrypt加密后的密码'),
    sa.Column('avatar', sa.String(length=500), nullable=True, comment='头像URL'),
    sa.Column('bio', sa.Text(), nullable=True, comment='个人简介'),
    sa.Column('storage_used', sa.BigInteger(), nullable=False, comment='已用存储空间，单位字节'),
    sa.Column('storage_quota', sa.BigInteger(), nullable=False, comment='存储配额，默认5GB，单位字节'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='文件或文件夹名称'),
    sa.Column('path', sa.Text(), nullable=False, comment='完整路径，如 /我的文档/图片'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父文件夹ID，为空则在根目录'),
    sa.Column('size', sa.BigInteger(), nullable=False, comment='文件大小，单位字节，文件夹为0'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='文件类型，如 image/png、video/mp4'),
    sa.Column('storage_key', sa.String(length=500), nullable=True, comment='MinIO中的存储路径，文件夹为空'),
    sa.Column('md5', sa.String(length=32), nullable=True, comment='文件MD5，用于秒传判断，文件夹为空'),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='所有者ID，关联users表'),
    sa.Column('is_dir', sa.Boolean(), nullable=False, comment='是否为文件夹'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除（软删除，进入回收站）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='文章标题'),
    sa.Column('slug', sa.String(length=255), nullable=False, comment='URL标识，唯一，由标题自动生成'),
    sa.Column('content', sa.Text(), nullable=True, comment='文章正文，Markdown格式'),
    sa.Column('summary', sa.Text(), nullable=True, comment='文章摘要'),
    sa.Column('cover_image', sa.String(length=500), nullable=True, comment='封面图URL'),
    sa.Column('author_id', sa.Integer(), nullable=False, comment='作者ID，关联users表'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='分类ID，关联categories表'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：draft草稿 / published已发布 / archived已归档'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='浏览次数'),
    sa.Column('like_count', sa.Integer(), nullable=False, comment='点赞次数'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='发布时间，草稿时为空'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('post_id', sa.Integer(), nullable=False, comment='所属文章ID，关联posts表'),
    sa.Column('author_id', sa.Integer(), nullable=False, comment='评论者ID，关联users表'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父评论ID，为空则是顶级评论'),
    sa.Column('content', sa.Text(), nullable=False, comment='评论内容'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：pending待审核 / approved已通过'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='评论时间'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=False, comment='文章ID'),
    sa.Column('tag_id', sa.Integer(), nullable=False, comment='标签ID'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    op.create_table('shares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('file_id', sa.Integer(), nullable=False, comment='分享的文件ID，关联files表'),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='分享者ID，关联users表'),
    sa.Column('token', sa.String(length=20), nullable=False, comment='分享短码，唯一，用于生成分享链接'),
    sa.Column('password', sa.String(length=100), nullable=True, comment='提取密码，为空则无需密码'),
    sa.Column('expire_at', sa.DateTime(), nullable=True, comment='过期时间，为空则永不过期'),
    sa.Column('download_count', sa.Integer(), nullable=False, comment='下载次数统计'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shares')
    op.drop_table('post_tags')
    op.drop_table('comments')
    op.drop_table('posts')
    op.drop_table('files')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('categories')
    # ### end Alembic commands ###
